name: project-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12.3
  - snakemake=9.4.0
  - biopython=1.83
  - matplotlib=3.8.4
  - pandas=2.2.2
  - numpy=1.26.4
  - jupyter
  - r-base
  - r-ggplot2
  - r-rmarkdown
  - r-reticulate
  - nb_conda_kernels
  - plotly=6.3.0
  - scipy=1.16.0
  - openpyxl
  - seaborn=0.13.2
  - bioinfokit=2.1.3
  - snakemake-executor-plugin-slurm=1.3.6
